#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
set -a; source "${script_dir}/.env.local"; set +a

workspace_dir="$(dirname "${script_dir}")"
cd "${workspace_dir}"

echo "==> Building development container..."
docker build -t "${DEV_WORKSPACE_IMAGE}" -f Dockerfile .
