#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
set -a; source "${script_dir}/.env.local"; set +a

workspace_dir="$(dirname "${script_dir}")"
cd "${workspace_dir}"

# Build the workspace image.
dev/build

# If NO_SSH is not set, start ssh-agent and add identities.
if [ -z "${NO_SSH:-}" ]; then
    echo "==> Starting ssh-agent..."
    eval "$(ssh-agent -s)" &> /dev/null
    ssh-add ~/.ssh/id_ed25519 &> /dev/null || true
fi

# Start and attach to the workspace container.
if [ -n "${CMD:-}" ]; then
    command=(bash -c "${CMD}")
else
    command=(bash)
fi
docker run -it --rm \
    --name "${DEV_WORKSPACE_NAME}" \
    --volume "${workspace_dir}:/workspace" \
    --workdir "/workspace" \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "${SSH_AUTH_SOCK}:/ssh-agent" \
    --env "SSH_AUTH_SOCK=/ssh-agent" \
    "${DEV_WORKSPACE_IMAGE}" \
    "${command[@]}"
