#!/bin/bash
set -eou pipefail
script_dir="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
set -a; source "${script_dir}/.env.local"; set +a

workspace_dir="$(dirname "${script_dir}")"
cd "${workspace_dir}"

# Build the workspace image.
dev/build

# Start and attach to the workspace container.
docker run -it --rm \
    --name "${DEV_WORKSPACE_NAME}" \
    --volume "${workspace_dir}:/workspace" \
    --workdir "/workspace" \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    "${DEV_WORKSPACE_IMAGE}"
